<a href="https://colab.research.google.com/github/PedroArroyoCruz/PedroArroyoCruz/blob/main/C%C3%B3pia_de_C%C3%B3pia_de_Untitled12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import plotly as plt

In [ ]:
df = pd.read_csv('/content/WDO$N_M15_2020.csv', sep ='\t')
df = df.drop(['<SPREAD>'],1)
df = df.drop(['<VOL>'],1)
df = df.drop(['<TICKVOL>'],1)
df.head(36)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  after removing the cwd from sys.path.

        <DATE>    <TIME>  <OPEN>  <HIGH>   <LOW>  <CLOSE>
0   2020.01.02  09:00:00  4016.5  4017.5  4008.5   4017.5
1   2020.01.02  09:15:00  4017.5  4024.0  4016.5   4019.0
2   2020.01.02  09:30:00  4019.0  4027.0  4016.0   4019.0
3   2020.01.02  09:45:00  4018.5  4020.0  4013.5   4014.5
4   2020.01.02  10:00:00  4015.0  4015.5  4008.5   4012.5
5   2020.01.02  10:15:00  4013.0  4017.0  4011.0   4013.0
6   2020.01.02  10:30:00  4013.0  4016.5  4012.0   4014.0
7   2020.01.02  10:45:00  4014.0  4018.0  4013.5   4016.5
8   2020.01.02  11:00:00  4017.0  4028.0  4016.0   4027.0
9   2020.01.02  11:15:00  4026.5  4037.5  4024.5   4036.0
10  2020.01.02  11:30:00  4035.5  4038.5  4031.0   4035.0
11  2020.01.02  11:45:00  4035.0  4035.5  4030.5   4032.0
12  2020.01.02  12:00:00  4032.0  4039.0  4032.0   4038.5
13  2020.01.02  12:15:00  4038.0  4043.0  4037.0   4037.0
14  2020.01.02  12:30:00  4037.5  4040.5  4036.0   4037.0
15  2020.01.02  12:45:00  4037.0  4040.5  4034.5   4035.5
16  2020.01.02  13:00:00  4035.5  4039.0  4035.0   4037.0
17  2020.01.02  13:15:00  4037.0  4043.0  4037.0   4039.0
18  2020.01.02  13:30:00  4039.0  4041.5  4038.5   4040.5
19  2020.01.02  13:45:00  4040.5  4046.0  4040.5   4042.5
20  2020.01.02  14:00:00  4043.0  4046.0  4042.0   4043.5
21  2020.01.02  14:15:00  4043.5  4044.5  4039.5   4040.0
22  2020.01.02  14:30:00  4040.0  4041.0  4035.5   4036.0
23  2020.01.02  14:45:00  4036.0  4040.0  4035.0   4039.0
24  2020.01.02  15:00:00  4039.0  4039.5  4037.5   4038.0
25  2020.01.02  15:15:00  4038.5  4040.0  4037.0   4039.5
26  2020.01.02  15:30:00  4039.0  4040.0  4035.0   4035.0
27  2020.01.02  15:45:00  4035.0  4037.0  4030.5   4031.5
28  2020.01.02  16:00:00  4031.5  4032.5  4029.5   4031.0
29  2020.01.02  16:15:00  4031.0  4031.0  4027.5   4029.5
30  2020.01.02  16:30:00  4029.5  4031.5  4026.5   4029.0
31  2020.01.02  16:45:00  4029.0  4031.0  4027.5   4029.5
32  2020.01.02  17:00:00  4029.0  4031.0  4026.0   4027.0
33  2020.01.02  17:15:00  4027.0  4027.5  4024.0   4024.0
34  2020.01.02  17:30:00  4024.0  4029.5  4022.5   4028.0
35  2020.01.02  17:45:00  4028.5  4031.0  4027.5   4029.0

In [ ]:
df.shape

(9075, 6)

In [ ]:
time = df.iloc[0:38,1].tolist()
time.pop()
time.append('18:15:00')
time

['09:00:00',
 '09:15:00',
 '09:30:00',
 '09:45:00',
 '10:00:00',
 '10:15:00',
 '10:30:00',
 '10:45:00',
 '11:00:00',
 '11:15:00',
 '11:30:00',
 '11:45:00',
 '12:00:00',
 '12:15:00',
 '12:30:00',
 '12:45:00',
 '13:00:00',
 '13:15:00',
 '13:30:00',
 '13:45:00',
 '14:00:00',
 '14:15:00',
 '14:30:00',
 '14:45:00',
 '15:00:00',
 '15:15:00',
 '15:30:00',
 '15:45:00',
 '16:00:00',
 '16:15:00',
 '16:30:00',
 '16:45:00',
 '17:00:00',
 '17:15:00',
 '17:30:00',
 '17:45:00',
 '18:00:00',
 '18:15:00']

In [ ]:
c = []
for i in time:
  index = df[df['<TIME>'] == i].index
  c.append(len(index))
for i in range(0,len(time)):
  print(time[i],'--',c[i])

09:00:00 -- 248
09:15:00 -- 248
09:30:00 -- 248
09:45:00 -- 248
10:00:00 -- 248
10:15:00 -- 248
10:30:00 -- 248
10:45:00 -- 248
11:00:00 -- 248
11:15:00 -- 248
11:30:00 -- 248
11:45:00 -- 248
12:00:00 -- 248
12:15:00 -- 248
12:30:00 -- 248
12:45:00 -- 248
13:00:00 -- 249
13:15:00 -- 249
13:30:00 -- 249
13:45:00 -- 249
14:00:00 -- 249
14:15:00 -- 249
14:30:00 -- 249
14:45:00 -- 249
15:00:00 -- 249
15:15:00 -- 249
15:30:00 -- 249
15:45:00 -- 249
16:00:00 -- 249
16:15:00 -- 249
16:30:00 -- 249
16:45:00 -- 249
17:00:00 -- 249
17:15:00 -- 249
17:30:00 -- 249
17:45:00 -- 249
18:00:00 -- 85
18:15:00 -- 42

In [ ]:
index_12_45_00 = df[df['<TIME>'] == '12:45:00'].index
index_13_00_00 = df[df['<TIME>'] == '13:00:00'].index
index_13_15_00 = df[df['<TIME>'] == '13:15:00'].index
index_13_30_00 = df[df['<TIME>'] == '13:30:00'].index
index_13_45_00 = df[df['<TIME>'] == '13:45:00'].index
index_14_00_00 = df[df['<TIME>'] == '14:00:00'].index
index_14_15_00 = df[df['<TIME>'] == '14:15:00'].index
index_14_30_00 = df[df['<TIME>'] == '14:30:00'].index
index_14_45_00 = df[df['<TIME>'] == '14:45:00'].index
index_15_00_00 = df[df['<TIME>'] == '15:00:00'].index
index_15_15_00 = df[df['<TIME>'] == '15:15:00'].index
index_15_30_00 = df[df['<TIME>'] == '15:30:00'].index
index_15_45_00 = df[df['<TIME>'] == '15:45:00'].index
index_16_00_00 = df[df['<TIME>'] == '16:00:00'].index
index_16_15_00 = df[df['<TIME>'] == '16:15:00'].index
index_16_30_00 = df[df['<TIME>'] == '16:30:00'].index
index_16_45_00 = df[df['<TIME>'] == '16:45:00'].index
index_17_00_00 = df[df['<TIME>'] == '17:00:00'].index
index_17_15_00 = df[df['<TIME>'] == '17:15:00'].index
index_17_30_00 = df[df['<TIME>'] == '17:30:00'].index
index_17_45_00 = df[df['<TIME>'] == '17:45:00'].index
index_18_00_00 = df[df['<TIME>'] == '18:00:00'].index
index_18_15_00 = df[df['<TIME>'] == '18:15:00'].index

In [ ]:
index_excluir = []

In [ ]:
for i in range(len(index_12_45_00)):
  if index_12_45_00[i] +  1 != index_13_00_00[i]:
    index_excluir.append(index_13_00_00[i])
  if index_12_45_00[i] + 2 != index_13_15_00[i]:
    index_excluir.append(index_13_15_00[i])
  if index_12_45_00[i] + 3 != index_13_30_00[i]:
    index_excluir.append(index_13_30_00[i])  
  if index_12_45_00[i] + 4 != index_13_45_00[i]:
    index_excluir.append(index_13_45_00[i])
  if index_12_45_00[i] + 5 != index_14_00_00[i]:
    index_excluir.append(index_14_00_00[i])
  if index_12_45_00[i] + 6 != index_14_15_00[i]:
    index_excluir.append(index_14_15_00[i])  
  if index_12_45_00[i] + 7 != index_14_30_00[i]:
    index_excluir.append(index_14_30_00[i])
  if index_12_45_00[i] + 8 != index_14_45_00[i]:
    index_excluir.append(index_14_45_00[i])
  if index_12_45_00[i] + 9 != index_15_00_00[i]:
    index_excluir.append(index_15_00_00[i])
  if index_12_45_00[i] + 10 != index_15_15_00[i]:
    index_excluir.append(index_15_15_00[i])
  if index_12_45_00[i] + 11 != index_15_30_00[i]:
    index_excluir.append(index_15_30_00[i])
  if index_12_45_00[i] + 12 != index_15_45_00[i]:
    index_excluir.append(index_15_45_00[i])
  if index_12_45_00[i] + 13 != index_16_00_00[i]:
    index_excluir.append(index_16_00_00[i])
  if index_12_45_00[i] + 14 != index_16_15_00[i]:
    index_excluir.append(index_16_15_00[i])  
  if index_12_45_00[i] + 15 != index_16_30_00[i]:
    index_excluir.append(index_16_30_00[i])
  if index_12_45_00[i] + 16 != index_16_45_00[i]:
    index_excluir.append(index_16_45_00[i])
  if index_12_45_00[i] + 17 != index_17_00_00[i]:
    index_excluir.append(index_17_00_00[i])
  if index_12_45_00[i] + 18 != index_17_15_00[i]:
    index_excluir.append(index_17_15_00[i])
  if index_12_45_00[i] + 19 != index_17_30_00[i]:
    index_excluir.append(index_17_30_00[i])
  if index_12_45_00[i] + 20 != index_17_45_00[i]:
    index_excluir.append(index_17_45_00[i])
    break

In [ ]:
for i in index_18_00_00:
  index_excluir.append(i)
for i in index_18_15_00:
  index_excluir.append(i)
len(index_excluir)

147

In [ ]:
df_248_dias = df.drop(df.index[index_excluir])
df_248_dias.shape

(8928, 6)

In [ ]:
df_248_dias['binario'] = df_248_dias['<CLOSE>'] - df_248_dias['<OPEN>']
df_248_dias['binario'] = df_248_dias['binario'].apply(lambda x: 1 if (x >=1) else (0))
df_248_dias.head(30)

        <DATE>    <TIME>  <OPEN>  <HIGH>   <LOW>  <CLOSE>  binario
0   2020.01.02  09:00:00  4016.5  4017.5  4008.5   4017.5        1
1   2020.01.02  09:15:00  4017.5  4024.0  4016.5   4019.0        1
2   2020.01.02  09:30:00  4019.0  4027.0  4016.0   4019.0        0
3   2020.01.02  09:45:00  4018.5  4020.0  4013.5   4014.5        0
4   2020.01.02  10:00:00  4015.0  4015.5  4008.5   4012.5        0
5   2020.01.02  10:15:00  4013.0  4017.0  4011.0   4013.0        0
6   2020.01.02  10:30:00  4013.0  4016.5  4012.0   4014.0        1
7   2020.01.02  10:45:00  4014.0  4018.0  4013.5   4016.5        1
8   2020.01.02  11:00:00  4017.0  4028.0  4016.0   4027.0        1
9   2020.01.02  11:15:00  4026.5  4037.5  4024.5   4036.0        1
10  2020.01.02  11:30:00  4035.5  4038.5  4031.0   4035.0        0
11  2020.01.02  11:45:00  4035.0  4035.5  4030.5   4032.0        0
12  2020.01.02  12:00:00  4032.0  4039.0  4032.0   4038.5        1
13  2020.01.02  12:15:00  4038.0  4043.0  4037.0   4037.0        0
14  2020.01.02  12:30:00  4037.5  4040.5  4036.0   4037.0        0
15  2020.01.02  12:45:00  4037.0  4040.5  4034.5   4035.5        0
16  2020.01.02  13:00:00  4035.5  4039.0  4035.0   4037.0        1
17  2020.01.02  13:15:00  4037.0  4043.0  4037.0   4039.0        1
18  2020.01.02  13:30:00  4039.0  4041.5  4038.5   4040.5        1
19  2020.01.02  13:45:00  4040.5  4046.0  4040.5   4042.5        1
20  2020.01.02  14:00:00  4043.0  4046.0  4042.0   4043.5        0
21  2020.01.02  14:15:00  4043.5  4044.5  4039.5   4040.0        0
22  2020.01.02  14:30:00  4040.0  4041.0  4035.5   4036.0        0
23  2020.01.02  14:45:00  4036.0  4040.0  4035.0   4039.0        1
24  2020.01.02  15:00:00  4039.0  4039.5  4037.5   4038.0        0
25  2020.01.02  15:15:00  4038.5  4040.0  4037.0   4039.5        1
26  2020.01.02  15:30:00  4039.0  4040.0  4035.0   4035.0        0
27  2020.01.02  15:45:00  4035.0  4037.0  4030.5   4031.5        0
28  2020.01.02  16:00:00  4031.5  4032.5  4029.5   4031.0        0
29  2020.01.02  16:15:00  4031.0  4031.0  4027.5   4029.5        0

In [ ]:
lst_df_248_dias = []

In [ ]:
for item in np.split(df_248_dias,248):
  lst_df_248_dias.append(item.values)

In [ ]:
lst_df_248_dias[0]

array([['2020.01.02', '09:00:00', 4016.5, 4017.5, 4008.5, 4017.5, 1],
       ['2020.01.02', '09:15:00', 4017.5, 4024.0, 4016.5, 4019.0, 1],
       ['2020.01.02', '09:30:00', 4019.0, 4027.0, 4016.0, 4019.0, 0],
       ['2020.01.02', '09:45:00', 4018.5, 4020.0, 4013.5, 4014.5, 0],
       ['2020.01.02', '10:00:00', 4015.0, 4015.5, 4008.5, 4012.5, 0],
       ['2020.01.02', '10:15:00', 4013.0, 4017.0, 4011.0, 4013.0, 0],
       ['2020.01.02', '10:30:00', 4013.0, 4016.5, 4012.0, 4014.0, 1],
       ['2020.01.02', '10:45:00', 4014.0, 4018.0, 4013.5, 4016.5, 1],
       ['2020.01.02', '11:00:00', 4017.0, 4028.0, 4016.0, 4027.0, 1],
       ['2020.01.02', '11:15:00', 4026.5, 4037.5, 4024.5, 4036.0, 1],
       ['2020.01.02', '11:30:00', 4035.5, 4038.5, 4031.0, 4035.0, 0],
       ['2020.01.02', '11:45:00', 4035.0, 4035.5, 4030.5, 4032.0, 0],
       ['2020.01.02', '12:00:00', 4032.0, 4039.0, 4032.0, 4038.5, 1],
       ['2020.01.02', '12:15:00', 4038.0, 4043.0, 4037.0, 4037.0, 0],
       ['2020.01.02', '12:30:00', 4037.5, 4040.5, 4036.0, 4037.0, 0],
       ['2020.01.02', '12:45:00', 4037.0, 4040.5, 4034.5, 4035.5, 0],
       ['2020.01.02', '13:00:00', 4035.5, 4039.0, 4035.0, 4037.0, 1],
       ['2020.01.02', '13:15:00', 4037.0, 4043.0, 4037.0, 4039.0, 1],
       ['2020.01.02', '13:30:00', 4039.0, 4041.5, 4038.5, 4040.5, 1],
       ['2020.01.02', '13:45:00', 4040.5, 4046.0, 4040.5, 4042.5, 1],
       ['2020.01.02', '14:00:00', 4043.0, 4046.0, 4042.0, 4043.5, 0],
       ['2020.01.02', '14:15:00', 4043.5, 4044.5, 4039.5, 4040.0, 0],
       ['2020.01.02', '14:30:00', 4040.0, 4041.0, 4035.5, 4036.0, 0],
       ['2020.01.02', '14:45:00', 4036.0, 4040.0, 4035.0, 4039.0, 1],
       ['2020.01.02', '15:00:00', 4039.0, 4039.5, 4037.5, 4038.0, 0],
       ['2020.01.02', '15:15:00', 4038.5, 4040.0, 4037.0, 4039.5, 1],
       ['2020.01.02', '15:30:00', 4039.0, 4040.0, 4035.0, 4035.0, 0],
       ['2020.01.02', '15:45:00', 4035.0, 4037.0, 4030.5, 4031.5, 0],
       ['2020.01.02', '16:00:00', 4031.5, 4032.5, 4029.5, 4031.0, 0],
       ['2020.01.02', '16:15:00', 4031.0, 4031.0, 4027.5, 4029.5, 0],
       ['2020.01.02', '16:30:00', 4029.5, 4031.5, 4026.5, 4029.0, 0],
       ['2020.01.02', '16:45:00', 4029.0, 4031.0, 4027.5, 4029.5, 0],
       ['2020.01.02', '17:00:00', 4029.0, 4031.0, 4026.0, 4027.0, 0],
       ['2020.01.02', '17:15:00', 4027.0, 4027.5, 4024.0, 4024.0, 0],
       ['2020.01.02', '17:30:00', 4024.0, 4029.5, 4022.5, 4028.0, 1],
       ['2020.01.02', '17:45:00', 4028.5, 4031.0, 4027.5, 4029.0, 0]],
      dtype=object)

In [ ]:
y_fech = []
y_max = []
y_min = []
lst_open_todos = []
max_open = []
dia = []
hora = []
lucro = []
max_open_todos = []

In [ ]:
for i in range(0,len(lst_df_248_dias)):
  for j in range(0,1):
    for k in range(1,36):
      lst_open_todos.append(lst_df_248_dias[i][k][2] -lst_df_248_dias[i][j][2])
      y_fech.append(lst_df_248_dias[i][k][5] -lst_df_248_dias[i][j][5])
      y_max.append(lst_df_248_dias[i][k][3] -lst_df_248_dias[i][j][3])
      y_min.append(lst_df_248_dias[i][k][4] -lst_df_248_dias[i][j][4])     
      dia.append(lst_df_248_dias[i][k][0])
      hora.append(lst_df_248_dias[i][k][1])
      lucro.append(lst_df_248_dias[i][k][5] - lst_df_248_dias[i][k][2])
      max_open.append(lst_df_248_dias[i][j][3] - lst_df_248_dias[i][j][2])
      max_open_todos.append(lst_df_248_dias[i][k][3] - lst_df_248_dias[i][k][2])

In [ ]:
df_regressão_1 = pd.DataFrame({'open': lst_open_todos,'max-open': max_open, 'max': y_max, 'min': y_min, 'fech': y_fech, 'lucro': lucro,'max_open_todos': max_open_todos, 'dia': dia, 'hora': hora})
df_regressão_1.head(36)

In [ ]:
from sklearn.model_selection import train_test_split
x1 = df_regressão_1.iloc[:, 0].values
y1 = df_regressão_1.iloc[:,2].values
x_train, x_teste, y_train, y_teste = train_test_split(x1,y1, test_size=0.25, random_state= 6)

In [ ]:
x1.shape, y1.shape

In [ ]:
x_train.shape, y_train.shape

In [ ]:
from sklearn.linear_model import LinearRegression
obj_linearregression = LinearRegression()
obj_linearregression.fit(x_train.reshape(-1,1), y_train.reshape(-1,1))
previsão_linear = obj_linearregression.predict(x_teste.reshape(-1,1))

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error
mean_absolute_error(y_teste, previsão_linear), mean_squared_error(y_teste, previsão_linear), np.sqrt(mean_squared_error(y_teste, previsão_linear))

In [ ]:
from yellowbrick.regressor import residuals_plot
viz = residuals_plot(obj_linearregression,x_train.reshape(-1,1), y_train.reshape(-1,1), x_teste.reshape(-1,1), y_teste.reshape(-1,1))

Validação Cruzada

In [ ]:
resultados_regressão = []
resultados_regressão_1 = []
from sklearn.model_selection import cross_val_score, KFold

In [ ]:
for i in range(30):
  obj_kfold = KFold(n_splits=10 , shuffle= True, random_state = i)
  regressão = LinearRegression()
  scores = cross_val_score(regressão, x1.reshape(-1,1), y1.reshape(-1,1), cv=obj_kfold, scoring='neg_mean_squared_error')
  scores_1 = cross_val_score(regressão, x1.reshape(-1,1), y1.reshape(-1,1), cv=obj_kfold, scoring='r2')
  resultados_regressão.append(-scores.mean())
  resultados_regressão_1.append(scores_1.mean())

In [ ]:
np.sqrt(np.mean(resultados_regressão)), np.mean(resultados_regressão_1)

(11.42617581972007, 0.9414419696368114)

Coeficientes

In [ ]:
print(f'intercepto : {obj_linearregression.intercept_} coeficiente angular{obj_linearregression.coef_}')

intercepto : [-5.38980611] coeficiente angular[[0.95584921]]